spring:
  datasource:
    url: jdbc:sqlserver://localhost:1435;databaseName=fullstack_test_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: StrongPassword123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: person  # <-- ensures Hibernate targets 'person' schema

  test:
    database:
      replace: none
